server:
  port: 4004

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webflux:
          routes:
            # === ONBOARDING SERVICE ROUTES ===
            - id: onboarding-service-hospitals
              uri: http://onboarding-service:4000
              predicates:
                - Path=/api/hospital/**
              filters:
                - name: DedupeResponseHeader
                  args:
                    name: Access-Control-Allow-Credentials Access-Control-Allow-Origin
                    strategy: RETAIN_FIRST

            - id: onboarding-service-plans
              uri: http://onboarding-service:4000
              predicates:
                - Path=/api/plans/**
              filters:
                - name: DedupeResponseHeader
                  args:
                    name: Access-Control-Allow-Credentials Access-Control-Allow-Origin
                    strategy: RETAIN_FIRST

            - id: onboarding-service-admin
              uri: http://onboarding-service:4000
              predicates:
                - Path=/api/admin/**
              filters:
                - name: DedupeResponseHeader
                  args:
                    name: Access-Control-Allow-Credentials Access-Control-Allow-Origin
                    strategy: RETAIN_FIRST

            # === AUTH SERVICE ROUTES ===
            - id: auth-service-login
              uri: http://auth-service:4001
              predicates:
                - Path=/auth/login
              filters:
                - name: DedupeResponseHeader
                  args:
                    name: Access-Control-Allow-Credentials Access-Control-Allow-Origin
                    strategy: RETAIN_FIRST

            - id: auth-service-register
              uri: http://auth-service:4001
              predicates:
                - Path=/auth/register
              filters:
                - name: DedupeResponseHeader
                  args:
                    name: Access-Control-Allow-Credentials Access-Control-Allow-Origin
                    strategy: RETAIN_FIRST

            - id: auth-service-validate
              uri: http://auth-service:4001
              predicates:
                - Path=/auth/validate
              filters:
                - name: DedupeResponseHeader
                  args:
                    name: Access-Control-Allow-Credentials Access-Control-Allow-Origin
                    strategy: RETAIN_FIRST

            - id: auth-service-health
              uri: http://auth-service:4001
              predicates:
                - Path=/auth/health
              filters:
                - name: DedupeResponseHeader
                  args:
                    name: Access-Control-Allow-Credentials Access-Control-Allow-Origin
                    strategy: RETAIN_FIRST

            # === HOSPITAL SERVICE ROUTES ===
            - id: hospital-service-users
              uri: http://hospital-service:4002
              predicates:
                - Path=/api/users/**
              filters:
                - name: DedupeResponseHeader
                  args:
                    name: Access-Control-Allow-Credentials Access-Control-Allow-Origin
                    strategy: RETAIN_FIRST

            - id: hospital-service-profile
              uri: http://hospital-service:4002
              predicates:
                - Path=/api/profile/**
              filters:
                - name: DedupeResponseHeader
                  args:
                    name: Access-Control-Allow-Credentials Access-Control-Allow-Origin
                    strategy: RETAIN_FIRST
          globals:
            cors-configurations:
              '[/**]':
                          allowed-origin-patterns:
                            - "*"
                          allowed-methods:
                            - GET
                            - POST
                            - PUT
                            - DELETE
                            - PATCH
                            - OPTIONS
                          allowed-headers:
                            - "*"
                          allow-credentials: true
                          max-age: 3600

      # === GLOBAL CORS CONFIGURATION ===
      # Disable service discovery (direct URLs used)
      discovery:
        locator:
          enabled: false

# === LOGGING CONFIG ===
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web: INFO
    reactor.netty.http.client: DEBUG
    org.springframework.cloud.gateway.handler.RoutePredicateHandlerMapping: TRACE

# === ACTUATOR CONFIG (FOR MONITORING) ===
management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
  endpoint:
    gateway:
      enabled: true
  health:
    show-details: always
