GRPC localhost:9001/AuthService/RegisterUser

{
  "email": "doctor.emma@healthconnect.com",
  "password": "SecurePass@2025",
  "hospitalId": 2,
  "tenantDb": "tenant_healthconnect",
  "globalRole": "HOSPITAL_ADMIN"
}